const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{fundo: 0},
	{botao: 0},
	{Toque: 0},
	{Sprite: 0},
	{Sólido: 0},
	{chao: 0},
	{Projétil: 0},
	{cobrinha: 0},
	{moeda: 0},
	{Plataforma: 0},
	{BoundTo: 0},
	{jogadorcaro: 0},
	{direita: 0},
	{esquerda: 0},
	{Partículas: 0},
	{Partículas2: 0},
	{Sprite2: 0},
	{Texto: 0},
	{Áudio: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{pontos: 0}
];

self.InstanceType = {
	fundo: class extends self.ISpriteInstance {},
	botao: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	cobrinha: class extends self.ISpriteInstance {},
	moeda: class extends self.ISpriteInstance {},
	jogadorcaro: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Partículas2: class extends self.IParticlesInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {}
}